### ISSUE TITLE
multi-line log messages attached to standard log lines

### ISSUE THREAD

**Issue by mbranyon** [signalfx/splunk-otel-collector-chart#309]
## What did you try to do?

Enable multilineConfigs to capture stack traces from java apps using the suggestion:
```
logsCollection:
  containers:
    enabled: true
    containerRuntime: "containerd"
    excludeAgentLogs: false
    multilineConfigs:
      - namespaceName:
          value: .*
          useRegexp: true
        firstEntryRegex: '^[^\s].*'
```

## What happened?

When looking at logs in the web interface, we see entries like the following, which obviously should not have java stack traces:
```
2021/11/18 23:30:44 [info] 3334#3334: *2688732 client closed connection while waiting for request, client: 10.128.26.129, server: 0.0.0.0:80
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1061)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1030)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:170)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:979)
	at org.springframework.boot.SpringApplication.close(SpringApplication.java:1305)
	at org.springframework.boot.SpringApplication.exit(SpringApplication.java:1292)
	at io.openraven.producer.scheduling.SchedulingEventsListener.lambda$discoverOnStartMaybe$0(SchedulingEventsListener.java:61)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
This particular log is from ingress-nginx. 

## What did you expect to happen?

I expect java traces not to be assigned log lines in seemingly random pods.

## Have you found any workaround?

I have not

## How impactful is the issue?

It makes me question the validity of any of the stored logs.

## How can we reproduce the issue?

The destination is `splunkPlatform`
The chart version is `0.37.1`
Helm Values:
```
clusterName: {{ $clusterName }}

splunkPlatform:
  endpoint: "https://<removed>/services/collector"
  token: <removed>
  index: product_k8s
  logsEnabled: true
  metricsEnabled: false
  metrics_index: product_k8s_metrics

logsEngine: otel

provider: "aws"

autodetect:
  prometheus: true
  istio: false

otelAgent:
  enabled: true
  resources:
    limits:
      cpu: 400m
      memory: 1Gi

otelK8sClusterReceiver:
  enabled: false

extraAttributes:
  custom:
    - name: cluster_name
      value: {{ $clusterName }}
    - name: group_id
      value: {{ $groupId }}
    - name: release_channel
      value: {{ $releaseChannel }}
    - name: release_version
      value: {{ $releaseInfo.releaseVersion }}

logsCollection:
  containers:
    enabled: true
    containerRuntime: "containerd"
    excludeAgentLogs: false
    multilineConfigs:
      - namespaceName:
          value: .*
          useRegexp: true
        firstEntryRegex: '^[^\s]'
```

**Comment by rockb1017** [comment]
hello, 
```
logsCollection:
  containers:
    enabled: true
    containerRuntime: "containerd"
    excludeAgentLogs: false
    multilineConfigs:
      - namespaceName:
          value: .*
          useRegexp: true
        firstEntryRegex: '^[^\s]'
```
you didn't specify any pod name or container name. 
then it will try to apply the same multiline configuration to all pods. 
I would suggest to provide pod name or container name. 

But anyways, i see your point. logs seem to be mixed up across multiple pods.

**Comment by rockb1017** [comment]
what is your cloud provider, container runtime, and kubernetes version?

**Comment by mbranyon** [comment]
This is in AWS, but is not using EKS, running on flatcar/containerd, and k8s version `1.19.8`

**Comment by rockb1017** [comment]
This has been a bug and its fix is merged. the next release that include that patch will fix this. 
https://github.com/open-telemetry/opentelemetry-log-collection/issues/276
