### ISSUE TITLE
Panic in splunk-otel-collector when running on AKS

### ISSUE THREAD

**Issue by phillipcaofph** [signalfx/splunk-otel-collector-chart#867]
## Description

Panic in `splunk-otel-collector` running on AKS causing pod to not start

## Steps to Reproduce

Deploy chart version 0.81.0 with the supplied chart configuration

### Chart version

v0.81.0

## Environment
Cloud: AKS
k8s version: 1.24.10/1.25.6

### Chart configuration

```yaml
clusterName: test
  splunkObservability:
    realm: us1
    logsEnabled: true
    accessToken: <token>
  distribution: aks
  cloudProvider: azure
  logsEngine: otel
```

### Log output

```shell
2023/08/02 00:03:30 settings.go:392: Set config to [/conf/relay.yaml]
2023/08/02 00:03:30 settings.go:445: Set ballast to 99 MiB
2023/08/02 00:03:30 settings.go:461: Set memory limit to 270 MiB
2023-08-02T00:03:30.509Z        info    service/telemetry.go:81 Setting up own telemetry...
2023-08-02T00:03:30.509Z        info    service/telemetry.go:104        Serving Prometheus metrics      {"address": "0.0.0.0:8889", "level": "Basic"}
2023-08-02T00:03:30.509Z        info    memorylimiterprocessor@v0.81.0/memorylimiter.go:102     Memory limiter configured       {"kind": "processor", "name": "memory_limiter", "pipeline": "logs/signalfx-events", "limit_mib": 270, "spike_limit_mib": 54, "check_interval": 2}
2023-08-02T00:03:30.510Z        info    kube/client.go:98       k8s filtering   {"kind": "processor", "name": "k8sattributes", "pipeline": "logs", "labelSelector": "", "fieldSelector": ""}
panic: interface conversion: internal.DetectorConfig is nil, not aks.Config

goroutine 1 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor/internal/azure/aks.NewDetector({{{0xc0009b10e0, 0x11}, {0x0, 0x0}}, {0xc0026ba0e0, {0x6877700, 0xc00249d280}, {0x68a1850, 0xc0024bf6b0}, 0x0, ...}, ...}, ...)
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor@v0.81.0/internal/azure/aks/aks.go:34 +0x10a
github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor/internal.(*ResourceProviderFactory).getDetectors(0xc000012bf0, {{{0xc0009b10e0, 0x11}, {0x0, 0x0}}, {0xc0026ba0e0, {0x6877700, 0xc00249d280}, {0x68a1850, 0xc0024bf6b0}, ...}, ...}, ...)
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor@v0.81.0/internal/resourcedetection.go:73 +0x182
github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor/internal.(*ResourceProviderFactory).CreateResourceProvider(0xc0026a5a40?, {{{0xc0009b10e0, 0x11}, {0x0, 0x0}}, {0xc0026ba0e0, {0x6877700, 0xc00249d280}, {0x68a1850, 0xc0024bf6b0}, ...}, ...}, ...)
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor@v0.81.0/internal/resourcedetection.go:49 +0x9d
github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor.(*factory).getResourceProvider(_, {{{0xc0009b10e0, 0x11}, {0x0, 0x0}}, {0xc0026ba0e0, {0x6877700, 0xc00249d280}, {0x68a1850, 0xc0024bf6b0}, ...}, ...}, ...)
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor@v0.81.0/factory.go:205 +0x3a5
github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor.(*factory).getResourceDetectionProcessor(0xc0026ae440?, {{{0xc0009b10e0, 0x11}, {0x0, 0x0}}, {0xc0026ba0e0, {0x6877700, 0xc00249d280}, {0x68a1850, 0xc0024bf6b0}, ...}, ...}, ...)
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor@v0.81.0/factory.go:173 +0x145
github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor.(*factory).createMetricsProcessor(0x7ff0fdffc5b8?, {0x68c3dd8, 0xc000082018}, {{{0xc0009b10e0, 0x11}, {0x0, 0x0}}, {0xc0026ba0e0, {0x6877700, 0xc00249d280}, ...}, ...}, ...)
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor@v0.81.0/factory.go:129 +0x9e
go.opentelemetry.io/collector/processor.CreateMetricsFunc.CreateMetricsProcessor(...)
        go.opentelemetry.io/collector/processor@v0.81.0/processor.go:122
go.opentelemetry.io/collector/processor.(*Builder).CreateMetrics(0xc0024bf670, {0x68c3dd8, 0xc000082018}, {{{0xc0009b10e0, 0x11}, {0x0, 0x0}}, {0xc0026ba0e0, {0x6877700, 0xc00249d280}, ...}, ...}, ...)
        go.opentelemetry.io/collector/processor@v0.81.0/processor.go:259 +0x16d
go.opentelemetry.io/collector/service/internal/graph.(*processorNode).buildComponent(0xc00248d4a0, {0x68c3dd8, 0xc000082018}, {0xc0024c8150, {0x6877700, 0xc00249d280}, {0x68a1850, 0xc0024bf6b0}, 0x0, {0xc0024c1b80}}, ...)
        go.opentelemetry.io/collector@v0.81.0/service/internal/graph/nodes.go:143 +0x45b
go.opentelemetry.io/collector/service/internal/graph.(*Graph).buildComponents(0xc0024bfe60, {0x68c3dd8, 0xc000082018}, {{0xc0024c8150, {0x6877700, 0xc00249d280}, {0x68a1850, 0xc0024bf6b0}, 0x0, {0xc0024c1b80}}, ...})
        go.opentelemetry.io/collector@v0.81.0/service/internal/graph/graph.go:179 +0x2a7
go.opentelemetry.io/collector/service/internal/graph.Build({0x68c3dd8, 0xc000082018}, {{0xc0024c8150, {0x6877700, 0xc00249d280}, {0x68a1850, 0xc0024bf6b0}, 0x0, {0xc0024c1b80}}, {{0x5d7f33b, ...}, ...}, ...})
        go.opentelemetry.io/collector@v0.81.0/service/internal/graph/graph.go:63 +0x3d0
go.opentelemetry.io/collector/service.(*Service).initExtensionsAndPipeline(_, {_, _}, {{{0x5d7f33b, 0x7}, {0x0, 0x0}, {0x68571c0, 0x7}}, 0xc0024bf660, ...}, ...)
        go.opentelemetry.io/collector@v0.81.0/service/service.go:204 +0x289
go.opentelemetry.io/collector/service.New({_, _}, {{{0x5d7f33b, 0x7}, {0x0, 0x0}, {0x68571c0, 0x7}}, 0xc0024bf660, 0xc0024bf670, ...}, ...)
        go.opentelemetry.io/collector@v0.81.0/service/service.go:117 +0x6f1
go.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents(0xc000769680, {0x68c3dd8, 0xc000082018})
        go.opentelemetry.io/collector@v0.81.0/otelcol/collector.go:155 +0x54b
go.opentelemetry.io/collector/otelcol.(*Collector).Run(0xc000769680, {0x68c3dd8, 0xc000082018})
        go.opentelemetry.io/collector@v0.81.0/otelcol/collector.go:207 +0x65
go.opentelemetry.io/collector/otelcol.NewCommand.func1(0xc002017800, {0x5d7fd7c?, 0x0?, 0x1?})
        go.opentelemetry.io/collector@v0.81.0/otelcol/command.go:27 +0x96
github.com/spf13/cobra.(*Command).execute(0xc002017800, {0xc000072050, 0x0, 0x1})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc002017800)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0xc0020bb980?)
        github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
main.runInteractive({{0xc0020bb980, 0xc0020bbb60, 0xc0020bbaa0, 0xc0020bb710, 0xc0020bbb90}, {{0x5d7f33b, 0x7}, {0x0, 0x0}, {0x68571c0, ...}}, ...})
        github.com/signalfx/splunk-otel-collector/cmd/otelcol/main.go:100 +0x5d
main.run(...)
        github.com/signalfx/splunk-otel-collector/cmd/otelcol/main_others.go:26
main.main()
        github.com/signalfx/splunk-otel-collector/cmd/otelcol/main.go:93 +0xcba
```

**Comment by omrozowicz-splunk** [comment]
Hello, it is related to a change in `resourcedetection` processor in the upstream, it is already fixed by: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24549 and will be a part of the next release.

Please downgrade to `0.80.0` for now, sorry for the inconvenience.

**Comment by phillipcaofph** [comment]
Thanks @omrozowicz-splunk !
